### ISSUE TITLE
Dimensions for notecarrier

### ISSUE THREAD

**Issue by gauteh** [sparkfunX/Qwiic_Cellular-Notecarrier#2]
Hi,

would you mind rendering a dimensions.pdf for the notecarrier?

Thank you, Gaute

**Comment by nseidle** [comment]
[Qwiic-Cellular-Notepad Dimensional Drawing.pdf](https://github.com/sparkfunX/Qwiic_Cellular-Notecarrier/files/7748075/Qwiic-Cellular-Notepad.Dimensional.Drawing.pdf)

Let me know if I missed a critical dimension anywhere.

**Comment by gauteh** [comment]
Thanks!

Gaute

man. 20. des. 2021, 22:40 skrev Nathan Seidle ***@***.***>:
